# Generated by Django 5.1 on 2024-10-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_userprofile_blood_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='health_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown Brand', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.TextField(default='Uncategorized'),
        ),
        migrations.AddField(
            model_name='product',
            name='common_name',
            field=models.CharField(default='Unnamed Product', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.TextField(blank=True, default='No labels', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.TextField(default='Unknown Packaging'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Ingredient', max_length=255)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_kj', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('energy_kcal', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('saturated_fat', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sugars', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('proteins', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('salt', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('serving_size', models.CharField(default='100g', max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_facts', to='product.product')),
            ],
        ),
    ]
