# Generated by Django 5.1 on 2024-10-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_health_rating_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging',
        ),
    ]
